### ISSUE TITLE
Inference Service

### ISSUE THREAD

**Issue by kavnish** [Open-Speech-EkStep/inference_service_wrapper#1]
I am following [these](https://github.com/Open-Speech-EkStep/inference_service/wiki) instruction to get the inference service running. 

But the [realtime_inference_service.py](https://github.com/Open-Speech-EkStep/inference_service/blob/main/realtime_inference_service.py) is failing with following error -- 

```
Traceback (most recent call last):
  File "/Users/avnish5.kumar/Desktop/projects/speech/inference_service/realtime_inference_service.py", line 11, in <module>
    from model_service import ModelService
  File "/Users/avnish5.kumar/Desktop/projects/speech/inference_service/model_service.py", line 3, in <module>
    from inverse_text_normalization.run_predict import inverse_normalize_text
ModuleNotFoundError: No module named 'inverse_text_normalization'
```

I can see "inverse_text_normalization" module was not found but this is also not present in the project directory. How are we suppose to get this module during execution?

-- I ran the setup script before running the realtime_inference_service.py script.

**Comment by kavnish** [comment]
There is a typo in [setup_new_env.sh](https://github.com/Open-Speech-EkStep/inference_service/blob/main/setup_new_env.sh)

In line3 creating a conda environment "fairseq3"
but in line4 activating conda "fairseq" [apparently I had "fairseq" env present that's why it didn't return any error.. kind of a silent fail]

![image](https://user-images.githubusercontent.com/35489661/141424082-74cd1cfd-bd51-4fd4-933a-537d643d5235.png)

**Comment by kavnish** [comment]
There is a typo in [setup_new_env.sh](https://github.com/Open-Speech-EkStep/inference_service/blob/main/setup_new_env.sh)

In line3 creating a conda environment "fairseq3"
but in line4 activating conda "fairseq" [apparently I had "fairseq" env present that's why it didn't return any error.. kind of a silent fail]

![image](https://user-images.githubusercontent.com/35489661/141424082-74cd1cfd-bd51-4fd4-933a-537d643d5235.png)
